### ISSUE TITLE
Setup node server + connect node server to postgresDB

### ISSUE THREAD

**Issue by hungnguyen3** [hungnguyen3/Giffy#1]
- set up node server with typescript: [tutorial](https://www.youtube.com/watch?v=1UcLoOD1lRM&ab_channel=BenAwad)
- connect node server to postgresDB using npm package `pg`: [pg website](https://node-postgres.com/)

**Comment by chiashenglin0204** [comment]
Will do: watch the tutorial for node server set up
I have a Physics midterm tomorrow hopefully I don't need to spend too much time on that
