### ISSUE TITLE
Server basic API endpoints

### ISSUE THREAD

**Issue by hungnguyen3** [hungnguyen3/Giffy#5]
- [x] Implement endpoints to do basic CRUD for table users
- [x] Implement endpoints to do basic CRUD for table collections
- [ ] Implement endpoints to do basic CRUD for table giffies
- [ ] Implement endpoints to do basic CRUD for table collections_users

**Comment by chiashenglin0204** [comment]
I will start doing table users today :)

**Comment by hungnguyen3** [comment]
> I will start doing table users today :)

good luck! I'm free on discord at night!

**Comment by chiashenglin0204** [comment]
I little bit busy this week but I will start doing CURD for table giffies
Also, could you change the project name to Giffy?

**Comment by hungnguyen3** [comment]
> I little bit busy this week but I will start doing CURD for table giffies Also, could you change the project name to Giffy?

Okay 👌 no problem! Final exams 🥲. I'll change it tmr
